name: Cypress Tests
on:
 push:
   branches:
     - main
     - integration
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
       if: failure()
       with:
         name: cypress-screenshots
         path: ./cypress/screenshots
       
       if: always()
       with:
         name: cypress-videos
         path: ./cypress/videos
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome